services:
  scenario-postgres:
    image: postgres:16
    container_name: scenario-postgres
    ports:
      - "5433:5432"
    volumes:
      - scenario-postgres-data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    networks:
      - scenario-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d dev_db"]
      interval: 5s
      retries: 5

  scenario-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: scenario-api
    volumes:
      - ./app:/scenario/app
    environment:
      - DOCKERIZED=true
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - scenario-network
    depends_on:
      scenario-postgres:
        condition: service_healthy

volumes:
  scenario-postgres-data: