"""0001_init_database

Revision ID: 934d94419217
Revises: 
Create Date: 2025-08-30 20:56:44.599704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934d94419217'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('password_token', sa.String(), nullable=True),
    sa.Column('profile_banner', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_model_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_model_username'), ['username'], unique=True)

    op.create_table('view_model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('genre_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=False),
    sa.Column('backdrop_path', sa.String(), nullable=False),
    sa.Column('release_date', sa.String(), nullable=False),
    sa.Column('release_year', sa.String(), nullable=False),
    sa.Column('runtime', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('viewer_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['viewer_id'], ['user_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('view_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_view_model_media_type'), ['media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_view_model_release_year'), ['release_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_view_model_tmdb_id'), ['tmdb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_view_model_viewer_id'), ['viewer_id'], unique=False)

    op.create_table('watchlist_model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_model_author_id'), ['author_id'], unique=False)

    op.create_table('media_model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('genre_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=False),
    sa.Column('backdrop_path', sa.String(), nullable=False),
    sa.Column('release_date', sa.String(), nullable=False),
    sa.Column('runtime', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_model_media_type'), ['media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_model_tmdb_id'), ['tmdb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_model_watchlist_id'), ['watchlist_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_model_watchlist_id'))
        batch_op.drop_index(batch_op.f('ix_media_model_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_media_model_media_type'))

    op.drop_table('media_model')
    with op.batch_alter_table('watchlist_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_model_author_id'))

    op.drop_table('watchlist_model')
    with op.batch_alter_table('view_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_view_model_viewer_id'))
        batch_op.drop_index(batch_op.f('ix_view_model_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_view_model_release_year'))
        batch_op.drop_index(batch_op.f('ix_view_model_media_type'))

    op.drop_table('view_model')
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_model_username'))
        batch_op.drop_index(batch_op.f('ix_user_model_email'))

    op.drop_table('user_model')
    # ### end Alembic commands ###
