name: "[PROD]: Compile and Push 'API' image"

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-api-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx

      - uses: docker/build-push-action@v5
        name: Build and push
        with:
          context: ./
          file: ./Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY_NAME }}:api-latest
